import React from 'react';
import { Download, FileText, CheckCircle2, ChevronRight } from 'lucide-react';
import Markdown from 'react-markdown';
import { useAuthAction } from '../lib/auth';
import { useSessions } from '../lib/sessions';

const ExecutiveBrief: React.FC = () => {
  const withAuth = useAuthAction();
  const { activeSession } = useSessions();
  const briefData = activeSession?.analysisData?.executiveBrief;

  let markdownContent = "No AI analysis available. Please complete VDR Ingestion to generate the executive brief.";
  
  if (briefData && briefData.executiveSummary) {
    markdownContent = `## Executive Summary
${briefData.executiveSummary}

### Critical Flag / Priority Risk Matrix
${briefData.redFlags ? briefData.redFlags.map((flag: string) => `* **Risk Element**: ${flag}`).join('\n') : '* No critical red flags supplied by AI Analysis'}

---

## Conclusion & Next Steps
**Executive Verdict:** ${briefData.goNoGoRecommendation || 'Proceed carefully'}
**Weighted Composite Risk Score:** ${briefData.confidenceScore || 80}/100`;

    if ((briefData.confidenceScore || 80) > 70) {
      markdownContent += `\n\n⚠️ **AUTOMATIC LOCK/ESCALATION**: Risk score of ${(briefData.confidenceScore || 80)}/100 exceeds the maximum safety threshold of 70. Proceeding further requires explicit signed authorization from both the Corporate General Counsel and CFO.`;
    }
  }

  return (
    <div className="flex flex-col items-center p-6 bg-stone-100 min-h-[calc(100vh-4rem)]">
      <div className="max-w-4xl w-full flex justify-between items-center mb-6">
          <div>
            <h1 className="text-2xl font-serif font-semibold text-stone-900">Executive Briefing</h1>
            <p className="text-stone-500 text-sm mt-1">Final brief generated by Risk Synthesis (Agent 5) and Executive Arbitrator (Agent 6)</p>
          </div>
          <div className="flex gap-3">
              <button onClick={withAuth(() => {})} className="flex items-center gap-2 px-4 py-2 bg-white border border-stone-200 text-stone-700 text-sm font-medium rounded-md hover:bg-stone-50 transition-colors shadow-sm">
                  <Download size={16} /> Adjusted Model
              </button>
              <button onClick={withAuth(() => {})} className="flex items-center gap-2 px-4 py-2 bg-[#bb6cff] text-white text-sm font-medium rounded-md hover:bg-[#a952f2] transition-colors shadow-sm">
                  <FileText size={16} /> Export PDF Brief
              </button>
          </div>
      </div>

      <div className="bg-white max-w-4xl w-full rounded-xl shadow-lg border border-stone-200 overflow-hidden relative">
          
          <div className="h-2 bg-stone-900 w-full absolute top-0 left-0"></div>
          
          <div className="px-10 py-12 pt-16">
             <div className="flex justify-between items-start border-b border-stone-200 pb-8 mb-8">
                <div>
                   <div className="w-8 h-8 bg-stone-900 rounded flex items-center justify-center text-white font-serif font-bold text-lg mb-4">
                       V
                   </div>
                   <h2 className="text-3xl font-serif text-stone-900 mb-2">{activeSession?.name || 'Project Phoenix'}</h2>
                   <p className="text-stone-500 tracking-wider text-sm uppercase">Due Diligence Memorandum</p>
                </div>
                <div className="text-right text-sm text-stone-500">
                    <p className="font-bold text-stone-900 mb-1">CONFIDENTIAL</p>
                    <p>Generated: Today</p>
                    <p>Status: <span className="text-amber-600 font-semibold">{briefData ? 'AI Verified' : 'Conditional Go'}</span></p>
                </div>
             </div>

             <div className="prose prose-stone max-w-none prose-headings:font-serif prose-h2:text-2xl prose-h2:border-b prose-h2:border-stone-100 prose-h2:pb-2 prose-h3:text-lg prose-strong:text-stone-900">
                <Markdown>{markdownContent}</Markdown>
             </div>
          </div>
          
          <div className="bg-stone-50 border-t border-stone-200 p-6 flex justify-between items-center text-xs text-stone-500 uppercase tracking-widest font-semibold">
              <span>Valence Engine v2.4</span>
              <span className="flex items-center gap-1"><CheckCircle2 size={14} className="text-green-600" /> Cryptographically Verified</span>
          </div>
      </div>
    </div>
  );
};

export default ExecutiveBrief;
